# Generated by Django 3.0.5 on 2021-01-25 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210124_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mess',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
